#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff

# Fix Emacs tiling
yabai -m rule --add app=Emacs manage=on

# Autofocus mouse
yabai -m config focus_follows_mouse autofocus

yabai -m config layout bsp

#--------------------
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9




yabai -m config window_border               off
yabai -m config window_border_width         2
#yabai -m config active_window_border_color  "${color["focused"]}"
#yabai -m config normal_window_border_color  "${color["normal"]}"
#yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize


# ===== RULES ======
yabai -m rule --add label="WhatsApp" app="^WhatsApp$" manage=off
yabai -m rule --add label="Microsoft Word" app="^Microsoft Word$" manage=off
